import { Topic } from "@/types";

export const TOPICS: Topic[] = [
  {
    id: "fundamentals",
    topicNumber: 1,
    title: "Fundamental Concepts",
    subtitle: "Core UI Building Blocks",
    description:
      "Learn essential React Native components: Text, View, Image, Button, TouchableHighlight, Pressable, and the Alert API.",
    category: "fundamentals",
    status: "completed",
    route: "/topics/fundamentals",
    icon: "🧩",
    keyConcepts: [
      "Text & Text Styling",
      "View Container",
      "Image & Remote Loading",
      "Button Component",
      "TouchableHighlight vs Pressable",
      "Alert API Triggers",
    ],
  },
  {
    id: "styling",
    topicNumber: 2,
    title: "Styling & Flexbox",
    subtitle: "Layouts & Responsive Design",
    description:
      "Master layout styling: StyleSheet vs Inline vs JS Object, flexDirection, justifyContent, alignItems, alignSelf, flexWrap, and flexGrow.",
    category: "styling",
    status: "completed",
    route: "/topics/styling",
    icon: "🎨",
    keyConcepts: [
      "StyleSheet vs Inline Styles",
      "Flex Direction (row / column)",
      "Justify Content Alignment",
      "Align Items & Align Self",
      "Flex Wrap & Multi-line rows",
      "Flex Grow dynamic distribution",
    ],
  },
  {
    id: "scrollview",
    topicNumber: 3,
    title: "ScrollView",
    subtitle: "Scrollable Containers & Keyboards",
    description:
      "Explore ScrollView for scrollable content, keyboard handling with KeyboardAvoidingView, keyboard dismiss on tap, and scroll indicators.",
    category: "scrollview",
    status: "completed",
    route: "/topics/scrollview",
    icon: "📜",
    keyConcepts: [
      "Vertical & Horizontal ScrollView",
      "showsVerticalScrollIndicator",
      "keyboardShouldPersistTaps",
      "Keyboard.dismiss on Touch",
      "Safe Area Insets integration",
    ],
  },
  {
    id: "flatlist",
    topicNumber: 4,
    title: "FlatList",
    subtitle: "High-Performance Data Lists",
    description:
      "Efficient large list rendering using FlatList, keyExtractor, numColumns grid layouts, ItemSeparatorComponent, and performance tips.",
    category: "flatlist",
    status: "completed",
    route: "/topics/flatlist",
    icon: "⚡",
    keyConcepts: [
      "FlatList vs ScrollView comparison",
      "renderItem & keyExtractor",
      "Grid Layout with numColumns",
      "columnWrapperStyle & Separator",
      "Performance optimization",
    ],
  },
  {
    id: "user-input",
    topicNumber: 5,
    title: "Handling User Input",
    subtitle: "Forms & Interactive Inputs",
    description:
      "Capture user text inputs, handle single line & multiline text, manage input state, set keyboard types, and control submission keys.",
    category: "input",
    status: "completed",
    route: "/topics/user-input",
    icon: "✍️",
    keyConcepts: [
      "TextInput Component",
      "State Binding with useState",
      "Single Line vs Multiline",
      "Keyboard Types (email, phone, numeric)",
      "Submit Editing & Return Keys",
    ],
  },
  {
    id: "stack-navigation",
    topicNumber: 6,
    title: "Stack Navigation",
    subtitle: "Screen Stack & Parameter Passing",
    description:
      "Navigate between screens using Expo Router Stack, customize screen headers, pass route parameters dynamically, and manage back navigation.",
    category: "navigation",
    status: "completed",
    route: "/topics/stack-navigation",
    icon: "📚",
    keyConcepts: [
      "Expo Router Stack Layout",
      "Pushing & Popping Screens",
      "Dynamic Route Params (/details/[id])",
      "Header Customization & Titles",
      "Back Button & Stack History",
    ],
  },
  {
    id: "tab-navigation",
    topicNumber: 7,
    title: "Tab Navigation",
    subtitle: "Bottom Navigation Bar",
    description:
      "Organize screens with Bottom Tab Navigation, tab icons, active/inactive color customization, tab titles, and tab layout group.",
    category: "navigation",
    status: "completed",
    route: "/(tabs)",
    icon: "🗂️",
    keyConcepts: [
      "Expo Router (tabs) Group",
      "Tabs Layout (_layout.tsx)",
      "Tab Icons & Active Badges",
      "Tab Title & Header Config",
      "Switching between Tab Screens",
    ],
  },
];
